import { v4 as uuidv4 } from "uuid";

const mockwines = [
  {
    id: uuidv4(),
    name: "Cabernet Sauvignon",
    price: 30.99,
    type: "red",
    relevance: 80,
    imageLink:
      "https://line39wines.com/cdn/shop/products/Line39_19Cab.png?v=1692278225&width=1500",
    country: "USA",
    location: "California",
    description:
      "A rich and full-bodied red wine with notes of blackcurrant and cedar.",
    grapeVariety: "Pinot Grigio",
    tasteCategory: "Semi-sweet",
    foodPairing: "Cheese",
    year: 2009,
    alcoholPercentage: 8,
    size: "750ml",
    sugarContent: "17 g/l",
    inStock: 50,
  },
  {
    id: uuidv4(),
    name: "Chardonnay",
    price: 25.49,
    type: "white",
    relevance: 85,
    imageLink:
      "https://freshvinewine.com/content/productimage/1_CHARDONNAY_SLIDER-min.png",
    country: "France",
    location: "Burgundy",
    description:
      "A crisp and elegant white wine with flavors of green apple and citrus.",
    grapeVariety: "Pinot Grigio",
    tasteCategory: "Semi-sweet",
    foodPairing: "Fish and seafood",
    year: 2021,
    alcoholPercentage: 9,
    size: "750ml",
    sugarContent: "15 g/l",
    inStock: 89,
  },
  {
    id: uuidv4(),
    name: "Merlot",
    price: 22.99,
    type: "red",
    relevance: 90,
    imageLink:
      "https://www.jeffersonvineyards.com/assets/images/products/pictures/OUTSHINERY-Jefferson-Merlot-2022.png",
    country: "Italy",
    location: "Tuscany",
    description:
      "A smooth and velvety red wine with hints of plum and chocolate.",
    grapeVariety: "Merlot",
    tasteCategory: "Dry",
    foodPairing: "Red or white meat",
    year: 2001,
    alcoholPercentage: 13,
    size: "750ml",
    sugarContent: "10 g/l",
    inStock: 38,
  },
  {
    id: uuidv4(),
    name: "Pinot Noir",
    price: 35.75,
    type: "red",
    relevance: 75,
    imageLink:
      "https://www.maset.com/cdnassets/products/red-wines/lg/bottle/pinot-noir-lg-1.png",
    country: "USA",
    location: "Oregon",
    description:
      "An elegant and delicate red wine with flavors of cherry and earth.",
    grapeVariety: "Pinot Noir",
    tasteCategory: "Dry",
    foodPairing: "Red or white meat",
    year: 1999,
    alcoholPercentage: 15,
    size: "750ml",
    sugarContent: "7 g/l",
    inStock: 15,
  },
  {
    id: uuidv4(),
    name: "Sauvignon Blanc",
    price: 27.5,
    type: "white",
    relevance: 80,
    imageLink:
      "https://www.sauvignonjohn.com/cdn/shop/products/image_65e4f397-1371-472c-a123-075ddd391ca0_1200x1200.png?v=1661873388",
    country: "New Zealand",
    location: "Marlborough",
    description:
      "A vibrant and refreshing white wine with tropical fruit and herbal notes.",
    grapeVariety: "Sauvignon Blanc",
    tasteCategory: "Semi-sweet",
    foodPairing: "Fish and seafood",
    year: 2015,
    alcoholPercentage: 9,
    size: "750ml",
    sugarContent: "17 g/l",
    inStock: 10,
  },
  {
    id: uuidv4(),
    name: "Chateau Latour",
    price: 84.75,
    type: "red",
    relevance: 95,
    imageLink:
      "https://www.12bouteilles.com/10414-medium_default/chateau-latour-2008.jpg",
    country: "France",
    location: "Bordeaux",
    description:
      "This wine is one of the most sought after and famous because it is produced from the best vineyards of Enclos, the incomparable historical terroir around Château Latour. Up to 4 grape varieties can be used in the composition of thisPauillac wine, Cabernet Sauvignon, Merlot, Cabernet Franc et Petit Verdot.",
    grapeVariety: "Chateau Latour",
    tasteCategory: "Dry",
    foodPairing: "Red or white meat",
    year: 2004,
    alcoholPercentage: 17,
    size: "750ml",
    sugarContent: "17 g/l",
    inStock: 57,
  },
  {
    id: uuidv4(),
    name: "Amarone Della Valpolicella",
    price: 27.5,
    type: "red",
    relevance: 80,
    imageLink:
      "https://astoriavinos.es/wp-content/uploads/2020/07/amarone-della-valpolicella-d-o-c-g-astoria-tinto.png",
    country: "Italy",
    location: "Valpolicella",
    description:
      "A vibrant and refreshing white wine with tropical fruit and herbal notes.",
    grapeVariety: "Valpolicella",
    tasteCategory: "Semi-dry",
    foodPairing: "Red or white meat",
    year: 2004,
    alcoholPercentage: 18,
    size: "750ml",
    sugarContent: "17 g/l",
    inStock: 27,
  },
];

export default mockwines;
